# MySQL version 5.x
development:
  adapter: mysql2
  encoding: UTF8
  database: slot_dev
  pool: 5
  username: root
  password: "clroot0987"
  host: 127.0.0.1
  port: 3306
  
test:
  adapter: mysql2
  encoding: UTF8
  database: slot_test
  pool: 5
  username: root
  password: "clroot0987"
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: UTF8
  database: slot
  pool: 5
  username: root
  password: "clroot0987"
  host: 127.0.0.1
  port: 3306
